version: "3"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media/plex/configs/sonarr:/config
      - /media/plex:/tv
      - /media/plex/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media/plex/configs/radarr:/config
      - /media/plex:/movies
      - /media/plex/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
    - /media/plex/configs/jackett:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    ports:
    - 9117:9117
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:8a915150-ls21
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error
    volumes:
      - /media/plex/configs/deluge:/config
      - /media/plex/torrents:/downloads
    ports:
    - 8112:8112
    restart: unless-stopped
