version: "3"

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:arm32v7-version-v0.2.0.1504
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    volumes:
      - ${CONFIG_PATH}/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/plex:/config
      - ${DATA_PATH}/media/Movies:/movies
      - ${DATA_PATH}/media/TV:/tv
    restart: unless-stopped
