version: "3"

services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped