version: "3"

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONFIG_PATH}/transmission:/config
      - ${DATA_PATH}/torrents:/downloads
      - ${DATA_PATH}/torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    ports:
      - 8989:8989

  radarr:
    ports:
      - 7878:7878

  jackett:
    ports:
      - 9117:9117

  plex:
    ports:
      - 32400:32400
